language: cpp

compiler:
  - gcc
#  - clang

dist: trusty
sudo: false

addons:
  apt:
    packages:
    - nasm
    - zip
    - libisl10
    - libcloog-isl4
    - texinfo
    - lua5.2
    - luarocks
    - parallel

before_install:
- lua util.lua grab-cross-compiler
- genisoimage --version || lua util.lua grab-genisoimage
- luarocks --help
- lua util.lua setup-luarocks

before_script:
- $(luarocks path)
- ls -laR $CROSSCOMPILERS_DIR
#  - travis_retry bundle
#  - if [ $TRAVIS_OS_NAME == linux ]; then travis_retry ./configure --llvm-config llvm-config-3.4; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then travis_retry ./configure; fi

script: lua vmakefile.lua -t all --mtune=corei7-avx --full

after_success:
- echo after success

before_deploy:
- echo before deploy
- sh disassemble-kernel.sh > .vmake/amd64.debug/beelzebub.beelzebub.amd64.disassembly.txt
- sh readelf-kernel.sh > .vmake/amd64.debug/beelzebub.beelzebub.amd64.readelf.txt
- pushd .vmake/amd64.debug
- zip -r Beelzebub.zip *
- popd

deploy:
  provider: releases
  api_key:
    secure: njiJBssMxtcacuaev8I5HZenqWw3HjC0v2Vmkn3iBaGUYU5Rdlm6c+Kv9lIDmTnqJ9bwOtrpJOfuyg5VaDBBjg4EPLugVwgSRUm7tGlrxlQv/5Af+qcBERVCQ92m6GTc1kWp59hAAmmfhak2YrKwZqtJ9qNnGRdgRfzCqdkhFgBAQiM2aIbS+188eBnN/8l3Y/l8gKlqsuqbLEWIxGTqzu8HOgGoIwrs0xGOok3KT9uPSYuI7WyR+WDIrSKYn5CjgN9VKjmEq1ag5n7ymwkMOsQdQwku8ws0aaQXuAeuAaT3UKBCXU3cYxrwEsnDPGK7cP0KcMJQONxHnpjWo67MMRfXWMu491xfZMwcxOiJUsLsMfQKJQt+s8pEqCEXM1qgmTNM7bf+Et4i1ZA2R0BTmeNCEcxQKjU8q6W2QA6mUVUlikkOwvwngsavjktsqCgQ/WjfMw2YC/adLD7kL+Tq5EKahoErCBjbbOv5oAvqiVLMj2Wi9yH8VEken14imNxN1xWn1zwOsNa4uyOQvOTahD8ugfUNATn0BctKEZ55AisiDuhBMjx0ooVsK1KZ4uUX31LeBv2HlcBCi9+eY5y5sN0O9MxuM0Ka+qOEbbOqJvMHzk2BdqO6HvCK3+MY3HmfTVk1/IdFPpgqtjHb9ETjBYv3mcMSagCFqsoglJvVj9Q=
  file: "build/Beelzebub.zip"
  on:
    repo: vercas/Beelzebub
    tags: true

after_deploy:
- echo after deploy

notifications:
  email: false
  irc:
    channels:
    - "chat.freenode.net##beelzebub"
    template:
    - "%{branch} - commit %{commit} by %{author} | %{build_url} | %{message}"

cache:
  directories:
  - $HOME/beelzebub-cross-compilers
  - $HOME/beelzebub-miscellaneous-tools

env:
  - LANG="en_US.UTF-8" CROSSCOMPILERS_DIR="$HOME/beelzebub-cross-compilers" MISC_TOOLS_DIR="$HOME/beelzebub-miscellaneous-tools"

os: linux
